# dataコンテナ
datastore:
  build: ./datastore


# nginx 1.11.5
nginx:
  build: ./nginx
  ports:
    - "8080:80"
  links:
    - php
  volumes_from:
    - datastore


# php:7.1-fpm
php:
  build: ./php
  # 別コンテナのエイリアスを設定 （リンク）
  links:
    - db
    - redis
    - memcached
  # [ホスト]：[コンテナ] ホストのディレクトリ以下をコンテナのパスにマウント
  volumes:
    - ./php/:/var/www/html/
    - /var/www/html/vender # Volume Trick
    - /var/www/html/application/views/templates # Volume Trick
    - /var/www/html/application/views/templates_c # Volume Trick


# db
db:
  build: .
  dockerfile: Dockerfile-db
  # 環境変数
  environment:
    MYSQL_ROOT_PASSWORD: root
  volumes:
    - ./test_db:/data/
    # - ./test_db:/docker-entrypoint-initdb.d/
  volumes_from:
    - datastore


# redis
redis:
  image: redis:3.0.7
  volumes_from:
    - datastore


# memcached
memcached:
  image: memcached:1.4.32


# phpmyadmin
phpmyadmin:
  image: phpmyadmin/phpmyadmin:4.6.4-1
  links:
    - db
  environment:
    - PMA_ARBITRARY=1
    - PMA_HOST=db
    - PMA_USER=root
    - PMA_PASSWORD=root