version: "3"
services:
  app:
    build: .
    ports:
      # - "5230:3000"
      - 127.0.0.1:5230:3000
    volumes:
      - ./app:/opt/app
      - /opt/app/node_modules
    links:
      # - mongo
      - db
  # mongo:
  #   image: mongo
  #   volumes:
  #     - ./data:/data/db
  #   ports:
  #     - "27017:27017"
  db:
    image: mysql:5.7.21
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root