CREATE DATABASE chat;
use chat;

CREATE TABLE comment (
	`id` INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	`name` VARCHAR(256),
	`room_id` INT NOT NULL
);

CREATE TABLE room (
	`id` INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	`name` VARCHAR(256)
);